server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wnbook?charaterEncode=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
logging:
  file:
    path: /logs/woniubook/ #位置：先找到项目运行的磁盘，然后在磁盘中创建一个目录logs,在logs中记录所有日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.woniuxy.operate.entity
#  global-config:
#    db-config:
#      logic-delete-field: delete_flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)